version: '3.8'

services:
  app:
    container_name: tsv-in-yaml
    image: 'mcr.microsoft.com/devcontainers/typescript-node:18-bullseye'
    volumes:
      - .:/workspace:cached

    working_dir: /workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
